name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jotoba:latest
    - name: upload
      run: |
        docker save -o jotoba_latest.tar jotoba:latest
        gzip jotoba_latest.tar
    - name: SCP Files
      uses: garygrossgarten/github-action-scp@release
      with:
          local: ./jotoba_latest.tar.gz
          remote: jotoba_latest.tar.gz
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
